/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsUuidGeneratorRouteImport } from './routes/tools/uuid-generator'
import { Route as ToolsUlidGeneratorRouteImport } from './routes/tools/ulid-generator'
import { Route as ToolsPasswordGeneratorRouteImport } from './routes/tools/password-generator'
import { Route as ToolsOgMetaSeoViewerRouteImport } from './routes/tools/og-meta-seo-viewer'
import { Route as ToolsJwtExtractRouteImport } from './routes/tools/jwt-extract'
import { Route as ToolsJsonViewerRouteImport } from './routes/tools/json-viewer'
import { Route as ToolsJsonToTypescriptRouteImport } from './routes/tools/json-to-typescript'
import { Route as ToolsImageConverterRouteImport } from './routes/tools/image-converter'
import { Route as ToolsBase64RouteImport } from './routes/tools/base64'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsUuidGeneratorRoute = ToolsUuidGeneratorRouteImport.update({
  id: '/tools/uuid-generator',
  path: '/tools/uuid-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsUlidGeneratorRoute = ToolsUlidGeneratorRouteImport.update({
  id: '/tools/ulid-generator',
  path: '/tools/ulid-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPasswordGeneratorRoute = ToolsPasswordGeneratorRouteImport.update({
  id: '/tools/password-generator',
  path: '/tools/password-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsOgMetaSeoViewerRoute = ToolsOgMetaSeoViewerRouteImport.update({
  id: '/tools/og-meta-seo-viewer',
  path: '/tools/og-meta-seo-viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsJwtExtractRoute = ToolsJwtExtractRouteImport.update({
  id: '/tools/jwt-extract',
  path: '/tools/jwt-extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsJsonViewerRoute = ToolsJsonViewerRouteImport.update({
  id: '/tools/json-viewer',
  path: '/tools/json-viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsJsonToTypescriptRoute = ToolsJsonToTypescriptRouteImport.update({
  id: '/tools/json-to-typescript',
  path: '/tools/json-to-typescript',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsImageConverterRoute = ToolsImageConverterRouteImport.update({
  id: '/tools/image-converter',
  path: '/tools/image-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBase64Route = ToolsBase64RouteImport.update({
  id: '/tools/base64',
  path: '/tools/base64',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/store': typeof DemoStoreRoute
  '/tools/base64': typeof ToolsBase64Route
  '/tools/image-converter': typeof ToolsImageConverterRoute
  '/tools/json-to-typescript': typeof ToolsJsonToTypescriptRoute
  '/tools/json-viewer': typeof ToolsJsonViewerRoute
  '/tools/jwt-extract': typeof ToolsJwtExtractRoute
  '/tools/og-meta-seo-viewer': typeof ToolsOgMetaSeoViewerRoute
  '/tools/password-generator': typeof ToolsPasswordGeneratorRoute
  '/tools/ulid-generator': typeof ToolsUlidGeneratorRoute
  '/tools/uuid-generator': typeof ToolsUuidGeneratorRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/store': typeof DemoStoreRoute
  '/tools/base64': typeof ToolsBase64Route
  '/tools/image-converter': typeof ToolsImageConverterRoute
  '/tools/json-to-typescript': typeof ToolsJsonToTypescriptRoute
  '/tools/json-viewer': typeof ToolsJsonViewerRoute
  '/tools/jwt-extract': typeof ToolsJwtExtractRoute
  '/tools/og-meta-seo-viewer': typeof ToolsOgMetaSeoViewerRoute
  '/tools/password-generator': typeof ToolsPasswordGeneratorRoute
  '/tools/ulid-generator': typeof ToolsUlidGeneratorRoute
  '/tools/uuid-generator': typeof ToolsUuidGeneratorRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/store': typeof DemoStoreRoute
  '/tools/base64': typeof ToolsBase64Route
  '/tools/image-converter': typeof ToolsImageConverterRoute
  '/tools/json-to-typescript': typeof ToolsJsonToTypescriptRoute
  '/tools/json-viewer': typeof ToolsJsonViewerRoute
  '/tools/jwt-extract': typeof ToolsJwtExtractRoute
  '/tools/og-meta-seo-viewer': typeof ToolsOgMetaSeoViewerRoute
  '/tools/password-generator': typeof ToolsPasswordGeneratorRoute
  '/tools/ulid-generator': typeof ToolsUlidGeneratorRoute
  '/tools/uuid-generator': typeof ToolsUuidGeneratorRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/store'
    | '/tools/base64'
    | '/tools/image-converter'
    | '/tools/json-to-typescript'
    | '/tools/json-viewer'
    | '/tools/jwt-extract'
    | '/tools/og-meta-seo-viewer'
    | '/tools/password-generator'
    | '/tools/ulid-generator'
    | '/tools/uuid-generator'
    | '/demo/api/names'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/store'
    | '/tools/base64'
    | '/tools/image-converter'
    | '/tools/json-to-typescript'
    | '/tools/json-viewer'
    | '/tools/jwt-extract'
    | '/tools/og-meta-seo-viewer'
    | '/tools/password-generator'
    | '/tools/ulid-generator'
    | '/tools/uuid-generator'
    | '/demo/api/names'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/demo/store'
    | '/tools/base64'
    | '/tools/image-converter'
    | '/tools/json-to-typescript'
    | '/tools/json-viewer'
    | '/tools/jwt-extract'
    | '/tools/og-meta-seo-viewer'
    | '/tools/password-generator'
    | '/tools/ulid-generator'
    | '/tools/uuid-generator'
    | '/demo/api/names'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoStoreRoute: typeof DemoStoreRoute
  ToolsBase64Route: typeof ToolsBase64Route
  ToolsImageConverterRoute: typeof ToolsImageConverterRoute
  ToolsJsonToTypescriptRoute: typeof ToolsJsonToTypescriptRoute
  ToolsJsonViewerRoute: typeof ToolsJsonViewerRoute
  ToolsJwtExtractRoute: typeof ToolsJwtExtractRoute
  ToolsOgMetaSeoViewerRoute: typeof ToolsOgMetaSeoViewerRoute
  ToolsPasswordGeneratorRoute: typeof ToolsPasswordGeneratorRoute
  ToolsUlidGeneratorRoute: typeof ToolsUlidGeneratorRoute
  ToolsUuidGeneratorRoute: typeof ToolsUuidGeneratorRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/uuid-generator': {
      id: '/tools/uuid-generator'
      path: '/tools/uuid-generator'
      fullPath: '/tools/uuid-generator'
      preLoaderRoute: typeof ToolsUuidGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/ulid-generator': {
      id: '/tools/ulid-generator'
      path: '/tools/ulid-generator'
      fullPath: '/tools/ulid-generator'
      preLoaderRoute: typeof ToolsUlidGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/password-generator': {
      id: '/tools/password-generator'
      path: '/tools/password-generator'
      fullPath: '/tools/password-generator'
      preLoaderRoute: typeof ToolsPasswordGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/og-meta-seo-viewer': {
      id: '/tools/og-meta-seo-viewer'
      path: '/tools/og-meta-seo-viewer'
      fullPath: '/tools/og-meta-seo-viewer'
      preLoaderRoute: typeof ToolsOgMetaSeoViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/jwt-extract': {
      id: '/tools/jwt-extract'
      path: '/tools/jwt-extract'
      fullPath: '/tools/jwt-extract'
      preLoaderRoute: typeof ToolsJwtExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/json-viewer': {
      id: '/tools/json-viewer'
      path: '/tools/json-viewer'
      fullPath: '/tools/json-viewer'
      preLoaderRoute: typeof ToolsJsonViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/json-to-typescript': {
      id: '/tools/json-to-typescript'
      path: '/tools/json-to-typescript'
      fullPath: '/tools/json-to-typescript'
      preLoaderRoute: typeof ToolsJsonToTypescriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/image-converter': {
      id: '/tools/image-converter'
      path: '/tools/image-converter'
      fullPath: '/tools/image-converter'
      preLoaderRoute: typeof ToolsImageConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/base64': {
      id: '/tools/base64'
      path: '/tools/base64'
      fullPath: '/tools/base64'
      preLoaderRoute: typeof ToolsBase64RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoStoreRoute: DemoStoreRoute,
  ToolsBase64Route: ToolsBase64Route,
  ToolsImageConverterRoute: ToolsImageConverterRoute,
  ToolsJsonToTypescriptRoute: ToolsJsonToTypescriptRoute,
  ToolsJsonViewerRoute: ToolsJsonViewerRoute,
  ToolsJwtExtractRoute: ToolsJwtExtractRoute,
  ToolsOgMetaSeoViewerRoute: ToolsOgMetaSeoViewerRoute,
  ToolsPasswordGeneratorRoute: ToolsPasswordGeneratorRoute,
  ToolsUlidGeneratorRoute: ToolsUlidGeneratorRoute,
  ToolsUuidGeneratorRoute: ToolsUuidGeneratorRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
